### ISSUE TITLE
Livereload client code

### ISSUE THREAD

**Issue by kadmil** [thgh/rollup-plugin-livereload#3]
Hello!

Thanks for the plugin! There's one thing I'm struggling with right now: I see that livereload's code is inlined, but livereload couldn't start and fail with exception: `livereload.js?snipver=1:855 LiveReload disabled because it could not find its own <SCRIPT> tag`. Why could it be?

**Comment by kadmil** [comment]
It seems like Chrome (as of 54th version) doesn't add `script` tags to `document.scripts` collection, thus livereload script fails

**Comment by thgh** [comment]
Would this technique help? https://github.com/thgh/rollup-plugin-livereload/commit/8c1516c5de6f4fd90c3d60dcc231ba84acbb7203

**Comment by kadmil** [comment]
I didn't anything with `window`, my code doesn't mention it in any way. As for technique, I'm getting away with manual livereload setup

**Comment by fes300** [comment]
same issue here

**Comment by soapdog** [comment]
Just confirming that this is still happening

**Comment by thgh** [comment]
This [fix](8c1516c8c1516c) has been released in v0.5.0

**Comment by brianfryer** [comment]
Confirming this issue is still happening in v0.6.0.

**Comment by zaceno** [comment]
Also confirming: still an issue

**Comment by zaceno** [comment]
My script tag is in the body of my html document, not the head. Could that be relevant?

**Comment by wikiwang1991** [comment]
No luck for me with v1.0.1 and chrome 75

livereload.js?snipver=1:1010 LiveReload disabled because it could not find its own <SCRIPT> tag
LiveReload @ livereload.js?snipver=1:1010
55../customevents @ livereload.js?snipver=1:1897
o @ livereload.js?snipver=1:1
r @ livereload.js?snipver=1:1
(anonymous) @ livereload.js?snipver=1:1

I notice there is `iframeDocument.write(lt + 'script' + gt + 'document.F=Object' + lt + '/script' + gt)` at line 333, is that a problem?
